### ISSUE TITLE
kubernetes Attempting reset: Failed.

### ISSUE THREAD

**Issue by liuxu623** [sorintlab/stolon#694]
### Submission type

 - Bug report

### Environment
kubernetes v1.15.3
#### Stolon version
v0.14.0
### Expected behaviour you didn't see
```
postgres=# select * from test;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```
### Unexpected behaviour you saw
```
postgres=# select * from test;
FATAL:  terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
### Steps to reproduce the problem
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Secret
metadata:
  name: stolon
  namespace: harbor
type: Opaque
data:
  pg_su_password: "********"
  pg_repl_password: "********"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon
  namespace: harbor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon
  namespace: harbor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - configmaps
      - events
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: stolon
  namespace: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stolon
subjects:
  - kind: ServiceAccount
    name: stolon
---
apiVersion: v1
kind: Service
metadata:
  name: stolon-keeper-headless
  namespace: harbor
spec:
  clusterIP: None
  ports:
    - name: keeper
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: stolon
    component: stolon-keeper
    stolon-cluster: stolon
---
apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy
  namespace: harbor
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: stolon
    component: stolon-proxy
    stolon-cluster: stolon
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: stolon-proxy
  namespace: harbor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stolon
      component: stolon-proxy
      stolon-cluster: stolon
  template:
    metadata:
      labels:
        app: stolon
        component: stolon-proxy
        stolon-cluster: stolon
    spec:
      serviceAccountName: stolon
      containers:
        - name: stolon
          image: "sorintlab/stolon:v0.14.0-pg11"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-ec"
            - |
              exec gosu stolon stolon-proxy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              value: stolon
            - name: STPROXY_STORE_BACKEND
              value: "kubernetes"
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            - name: STPROXY_DEBUG
              value: "false"
          ports:
            - name: metrics
              containerPort: 8080

            - name: stolon
              containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: stolon-sentinel
  namespace: harbor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stolon
      component: stolon-sentinel
      stolon-cluster: stolon
  template:
    metadata:
      labels:
        app: stolon
        component: stolon-sentinel
        stolon-cluster: stolon
    spec:
      serviceAccountName: stolon
      containers:
        - name: stolon
          image: "sorintlab/stolon:v0.14.0-pg11"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-ec"
            - |
              exec gosu stolon stolon-sentinel
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STSENTINEL_CLUSTER_NAME
              value: stolon
            - name: STSENTINEL_STORE_BACKEND
              value: "kubernetes"
            - name: STSENTINEL_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STSENTINEL_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            - name: STSENTINEL_DEBUG
              value: "false"
          ports:
            - name: metrics
              containerPort: 8080
            - name: stolon
              containerPort: 5432
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: stolon-keeper
  namespace: harbor
spec:
  serviceName: stolon-keeper-headless
  replicas: 3
  selector:
    matchLabels:
      app: stolon
      component: stolon-keeper
      stolon-cluster: stolon
  template:
    metadata:
      labels:
        app: stolon
        component: stolon-keeper
        stolon-cluster: stolon
    spec:
      serviceAccountName: stolon
      terminationGracePeriodSeconds: 10
      containers:
        - name: stolon
          image: "sorintlab/stolon:v0.14.0-pg11"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-ec"
            - |
              # Generate our keeper uid using the pod index
              IFS='-' read -ra ADDR <<< "$(hostname)"
              export STKEEPER_UID="keeper${ADDR[-1]}"
              export POD_IP=$(hostname -i)
              export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
              export STOLON_DATA=/stolon-data
              chown stolon:stolon $STOLON_DATA
              exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STKEEPER_CLUSTER_NAME
              value: stolon
            - name: STKEEPER_STORE_BACKEND
              value: "kubernetes"
            - name: STKEEPER_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STKEEPER_PG_REPL_USERNAME
              value: "repluser"
            - name: STKEEPER_PG_REPL_PASSWORDFILE
              value: "/etc/secrets/stolon/pg_repl_password"
            - name: STKEEPER_PG_SU_USERNAME
              value: "stolon"
            - name: STKEEPER_PG_SU_PASSWORDFILE
              value: "/etc/secrets/stolon/pg_su_password"
            - name: STKEEPER_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            - name: STKEEPER_DEBUG
              value: "false"
          ports:
            - name: metrics
              containerPort: 8080
            - name: stolon
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /stolon-data
            - name: stolon-secrets
              mountPath: /etc/secrets/stolon
      volumes:
        - name: stolon-secrets
          secret:
            secretName: stolon
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
        storageClassName: "rbd-fast"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-create-cluster
  namespace: harbor
spec:
  template:
    metadata:
      labels:
        app: stolon
    spec:
      restartPolicy: OnFailure
      serviceAccountName: stolon
      containers:
        - name: stolon-create-cluster
          image: "sorintlab/stolon:v0.14.0-pg11"
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/stolonctl"]
          args:
            - init
            - --cluster-name=stolon
            - --store-backend=kubernetes
            - --kube-resource-kind=configmap
            - --yes
            - '{ "initMode": "new", "synchronousReplication": true, "minSynchronousStandbys": 1, "maxSynchronousStandbys": 1, "sleepInterval": "1s", "failInterval": "5s", "pgParameters": {} }'
```
```
$ kubectl get pod -n harbor
NAME                              READY   STATUS      RESTARTS   AGE
stolon-create-cluster-rlc5n       0/1     Completed   0          2m41s
stolon-keeper-0                   1/1     Running     0          2m42s
stolon-keeper-1                   1/1     Running     0          2m30s
stolon-keeper-2                   1/1     Running     0          2m18s
stolon-proxy-7bf98dfff9-d2b5z     1/1     Running     0          2m43s
stolon-proxy-7bf98dfff9-h8nt5     1/1     Running     0          2m43s
stolon-proxy-7bf98dfff9-s9x5w     1/1     Running     0          2m43s
stolon-sentinel-75568d657-7lx28   1/1     Running     0          2m43s
stolon-sentinel-75568d657-8slt5   1/1     Running     0          2m43s
stolon-sentinel-75568d657-sz989   1/1     Running     0          2m43s
```
```
$ kubectl get svc -n harbor
NAME                     TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)    AGE
stolon-keeper-headless   ClusterIP   None              <none>        5432/TCP   13m
stolon-proxy             ClusterIP   192.168.134.211   <none>        5432/TCP   13m
```
```
$ psql --host 192.168.134.211 --port 5432 postgres -U stolon -W
postgres=# create table test (id int primary key not null, value text not null);
CREATE TABLE
postgres=# insert into test values (1, 'value1');
INSERT 0 1
postgres=# select * from test;
 id | value
----+--------
  1 | value1
(1 row)
```
```
$ kubectl delete statefulset stolon-keeper --cascade=false -n harbor
statefulset.apps "stolon-keeper" deleted
$ kubectl delete pod stolon-keeper-0 -n harbor
pod "stolon-keeper-0" deleted
```
```
postgres=# select * from test;
FATAL:  terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
```
2019-08-29T05:06:45.364Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:46.765Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:48.565Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:49.964Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:51.365Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:51.366Z	INFO	cmd/sentinel.go:980	master db is failed	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:51.366Z	INFO	cmd/sentinel.go:991	trying to find a new master to replace failed master
2019-08-29T05:06:51.367Z	INFO	cmd/sentinel.go:1017	electing db as the new master	{"db": "544628e1", "keeper": "keeper1"}
2019-08-29T05:06:52.765Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:52.767Z	INFO	cmd/sentinel.go:1097	waiting for proxies to be converged to the current generation	{"proxies": ["f22df292", "56434298", "fa5df53d"]}
2019-08-29T05:06:54.564Z	WARN	cmd/sentinel.go:270	no keeper info available	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:54.567Z	INFO	cmd/sentinel.go:1097	waiting for proxies to be converged to the current generation	{"proxies": ["56434298", "fa5df53d", "f22df292"]}
2019-08-29T05:06:54.567Z	INFO	cmd/sentinel.go:1136	removing old master db	{"db": "f12e56df", "keeper": "keeper0"}
2019-08-29T05:06:54.567Z	INFO	cmd/sentinel.go:1222	one of the new synchronousStandbys has been removed{"db": "f12e56df", "inSyncStandbys": [], "synchronousStandbys": ["f12e56df"]}
2019-08-29T05:06:54.567Z	INFO	cmd/sentinel.go:1234	setting the expected sync-standbys to the current known in sync sync-standbys	{"inSyncStandbys": [], "synchronousStandbys": ["f12e56df"]}
2019-08-29T05:06:54.567Z	INFO	cmd/sentinel.go:1380	using a fake synchronous standby since there are not enough real standbys available	{"masterDB": "544628e1", "required": 1}
2019-08-29T05:06:57.365Z	INFO	cmd/sentinel.go:1317	adding new synchronous standby in good state trying to reach MaxSynchronousStandbys	{"masterDB": "544628e1", "synchronousStandbyDB": "8065f29d", "keeper": "keeper2"}
2019-08-29T05:06:57.366Z	INFO	cmd/sentinel.go:1361	merging current and previous synchronous standbys	{"masterDB": "544628e1", "prevSynchronousStandbys": {}, "synchronousStandbys": {"8065f29d":{}}}
2019-08-29T05:06:57.366Z	INFO	cmd/sentinel.go:1373	synchronousStandbys changed	{"masterDB": "544628e1", "prevSynchronousStandbys": {}, "synchronousStandbys": {"8065f29d":{}}}
```
